// ─── REGIONAL AGENCY COMPARISON DATA ─────────────────────────────────────────
// All dollar values are monthly unless noted. Hourly uses 224 hrs/mo (56 hr/wk shift).
// null = data not yet collected. Update each agency as MOUs/salary schedules are reviewed.
// "Top Step" = top firefighter step (not Captain). "Top FF Medic" = top step + paramedic pay.

export const COLUMNS = [
  { key: "raise2026",            label: "2026 Raise",             format: "pct",    group: "Raises" },
  { key: "raise2027",            label: "2027 Raise",             format: "pct",    group: "Raises" },
  { key: "topStepHrly",          label: "Top Step Hrly",          format: "dollar", group: "Base Pay" },
  { key: "topStepMonthly",       label: "Top Step Monthly",       format: "dollar", group: "Base Pay" },
  { key: "topFFMedicHrly",       label: "Top FF+Medic Hrly",      format: "dollar", group: "Base Pay" },
  { key: "individualIncentives", label: "Individual Incentives",  format: "dollar", group: "Incentives" },
  { key: "operationalIncentives",label: "Operational Incentives", format: "dollar", group: "Incentives" },
  { key: "longevity10yr",        label: "Longevity 10yr",         format: "pct",    group: "Incentives" },
  { key: "deferredComp",         label: "Deferred Comp",          format: "dollar", group: "Benefits" },
  { key: "totalCash",            label: "Total Cash",             format: "dollar", group: "Benefits" },
  { key: "employeeRHS",          label: "Employee RHS",           format: "dollar", group: "Benefits" },
  { key: "cityRHS",              label: "City RHS Contribution",  format: "dollar", group: "Benefits" },
  { key: "medicalFamily",        label: "Medical (Family+2)",     format: "dollar", group: "Benefits" },
  { key: "dental",               label: "Dental",                 format: "dollar", group: "Benefits" },
  { key: "vision",               label: "Vision",                 format: "dollar", group: "Benefits" },
  { key: "ltd",                  label: "LTD",                    format: "dollar", group: "Benefits" },
  { key: "lifeInsurance",        label: "Life Insurance",         format: "dollar", group: "Benefits" },
  { key: "medicarePct",          label: "SS & Medicare (1.45%)",  format: "pct",    group: "Taxes & PERS" },
  { key: "persEEPct",            label: "% PERS Paid by EE",      format: "pct",    group: "Taxes & PERS" },
  { key: "cityPERSPaidByEE",     label: "City PERS Paid by EE",  format: "dollar", group: "Taxes & PERS" },
  { key: "monthlyGross",         label: "Monthly Gross",          format: "dollar", group: "Total" },
];

export const LOWER_IS_BETTER = new Set(["medicarePct", "persEEPct", "cityPERSPaidByEE"]);

export const AGENCIES = [
  {
    name: "Roseville Fire", shortName: "Roseville", highlight: true,
    persFormula: "Classic 3%@50 / PEPRA 2.7%@57",
    raise2026: 3.0, raise2027: 0,
    topStepHrly: 49.13, topStepMonthly: 11004.81, topFFMedicHrly: 56.01,
    individualIncentives: null, operationalIncentives: null, longevity10yr: 5.0,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Sacramento City Fire", shortName: "Sac City", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Sacramento Metro Fire", shortName: "Sac Metro", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Cosumnes CSD (Elk Grove)", shortName: "Cosumnes", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Folsom Fire", shortName: "Folsom", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Rocklin Fire", shortName: "Rocklin", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "El Dorado Hills Fire", shortName: "El Dorado Hills", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Vacaville Fire", shortName: "Vacaville", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Fairfield Fire", shortName: "Fairfield", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
  {
    name: "Livermore-Pleasanton Fire", shortName: "Livermore-Pleasanton", highlight: false,
    persFormula: null, raise2026: null, raise2027: null,
    topStepHrly: null, topStepMonthly: null, topFFMedicHrly: null,
    individualIncentives: null, operationalIncentives: null, longevity10yr: null,
    deferredComp: null, totalCash: null, employeeRHS: null, cityRHS: null,
    medicalFamily: null, dental: null, vision: null, ltd: null, lifeInsurance: null,
    medicarePct: 1.45, persEEPct: null, cityPERSPaidByEE: null, monthlyGross: null,
  },
];
